name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Create Firebase Config
      run: |
        echo '{
          "hosting": {
            "public": "public",
            "ignore": [
              "firebase.json",
              "**/.*",
              "**/node_modules/**"
            ],
            "rewrites": [
              {
                "source": "**",
                "destination": "/index.html"
              }
            ]
          }
        }' > firebase.json

    - name: Create Public Directory
      run: |
        mkdir -p public
        # Копируем HTML файлы в public директорию
        cp *.html public/ || true
        # Если файлы уже в public, это не нужно
        if [ ! -f public/index.html ]; then
          echo "Creating placeholder files"
          echo "<html><body><h1>Deployment in progress</h1></body></html>" > public/index.html
        fi

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
      env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks